on:
  pull_request:
    branches:
      - production
    types: [closed]

jobs:
  deploy_prd:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.head_ref, release)
    steps:
      - name: Create Prd Release Pull Request
        id: create_release_pr
        run: |
          ls
          pwd
          echo ${{github.base_ref}}
          echo `echo ${{ github.head_ref }} | sed -e "s/release\///"`
