on:
  push:
    branches: ["hotfix/*"]

jobs:
  create_hotfix_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Production Create Hotfix Pull Request
        id: production_create_hotfix_pr
        uses: repo-sync/pull-request@v2
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_title: ${BRANCH_NAME} for Production
          destination_branch: production
          source_branch: ${{ github.head_ref }}

      - name: Pre-Production Create Hotfix Pull Request
        id: preproduction_create_hotfix_pr
        uses: repo-sync/pull-request@v2
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr_title: ${BRANCH_NAME} for Pre-Production
          destination_branch: pre-production
          source_branch: ${{ github.head_ref }}
