on:
  push:
    branches: [main]

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Create Staging release pull Request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: production
          GIT_PR_RELEASE_BRANCH_STAGING: pre-production
          GIT_PR_RELEASE_LABELS: staging-release
        run: |
          gem install -N git-pr-release -v "1.4.0"
          git-pr-release --no-fetch
